/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.instructor;

import com.mycompany.CourseManagement.Course;
import com.mycompany.CourseManagement.Lesson;
import com.mycompany.UserAccountManagement.Instructor;
import com.mycompany.frontend.MainFrame;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class InstructorDashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form InstructorDashboardFrame
     */
    CardLayout cardLayout;
    JPanel cardsPanel;
    private Instructor instructor;

    public InstructorDashboardFrame(Instructor instructor) {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
                JOptionPane.showMessageDialog(mainFrame,"Logged Out Successfully","Successful Operation!", JOptionPane.INFORMATION_MESSAGE);
            }
        });
        
        this.instructor = instructor;
        initComponents();
        cardLayout = new CardLayout();
        cardsPanel = new JPanel(cardLayout);
        getContentPane().add(cardsPanel);
        showDashboard();
    }

    public InstructorDashboardFrame() {
        try {
            this.instructor = new Instructor("instructor1", "Default Instructor", "instructor@example.com", "password");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error initializing instructor: " + ex.getMessage());
        }
        initComponents();
        cardLayout = new CardLayout();
        cardsPanel = new JPanel(cardLayout);
        getContentPane().add(cardsPanel);
        showDashboard();
    }
     
    public void showDashboard() {
        DashboardPanel dashboard = new DashboardPanel(this, instructor);

        cardsPanel.add(dashboard, "DASHBOARD");

        cardLayout.show(cardsPanel, "DASHBOARD");
    }

    public void showCoursePanel(Course course) {
        CoursePanel cp = new CoursePanel(this, course, instructor);

        cardsPanel.add(cp, "COURSE");

        cardLayout.show(cardsPanel, "COURSE");
    }

    public void showLessonPanel(Lesson lesson, Course course) {
        LessonPanel lp = new LessonPanel(this, lesson, course, instructor);

        cardsPanel.add(lp, "LESSON");

        cardLayout.show(cardsPanel, "LESSON");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
