/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend.Main;

import com.mycompany.CourseManagement.CourseServices;
import com.mycompany.UserAccountManagement.Instructor;
import com.mycompany.UserAccountManagement.Student;
import com.mycompany.UserAccountManagement.UserServices;
import com.mycompany.frontend.InstructorDashboard.InstructorDashboardFrame;
import com.mycompany.frontend.StudentDashboard.StudentDashboardFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hazem
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private CardLayout cardLayout;
    private LoginPanel loginPanel;
    private SignupPanel signupPanel;
    private MainPanel mainPanel;
    private UserServices userServices;
    private CourseServices courseServices;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try
        {
            userServices = new UserServices();
            courseServices = new CourseServices();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage(), "Error",JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        setTitle("SkillForge Platform🔨");
        setSize(1280, 720);
        setMinimumSize(new Dimension(1280,720));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cardLayout = new CardLayout();
        setLayout(cardLayout);
        setBackground(Color.white);
        initComponents(); 
        
        mainPanel = new MainPanel(this);
        add(mainPanel,"home");
        
        loginPanel = new LoginPanel(this);
        add(loginPanel,"login");
        
        signupPanel = new SignupPanel(this);
        add(signupPanel, "signup");
        
        cardLayout.show(getContentPane(),"home");
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    public UserServices getUserServices() {
        return userServices;
    }

    public void setUserServices(UserServices userServices) {
        this.userServices = userServices;
    }

    public CourseServices getCourseServices() {
        return courseServices;
    }

    public void setCourseServices(CourseServices courseServices) {
        this.courseServices = courseServices;
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public LoginPanel getLoginPanel() {
        return loginPanel;
    }

    public SignupPanel getSignupPanel() {
        return signupPanel;
    }
    
    public MainPanel getMainPanel() {
        return mainPanel;
    }
    
    public void navigateToInstructorPanel(Instructor instructor)
    {
        InstructorDashboardFrame instructorDashboardFrame = new InstructorDashboardFrame(instructor);
        instructorDashboardFrame.setVisible(true);
        this.dispose();
    }
    
    public void navigateToStudentFrame(Student student)
    {
        StudentDashboardFrame studentDashboardFrame = new StudentDashboardFrame(student);
        studentDashboardFrame.setVisible(true);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
